### ISSUE TITLE
The code in utils is so weird, Can you give some explanation?

### ISSUE THREAD

**Issue by fooSynaptic** [ymfa/seq2seq-summarizer#6]
`class Example(NamedTuple):
  src: List[str]
  tgt: List[str]
  src_len: int  # inclusive of EOS, so that it corresponds to tensor shape
  tgt_len: int  # inclusive of EOS, so that it corresponds to tensor shape`

code above implemented nothing with class `Example`

**Comment by ymfa** [comment]
This is the definition of a NamedTuple. A NamedTuple is like a tuple but you can access its content by using field names in addition to indices [0], [1], etc. I use this structure to hold the data of each training or testing example. Because it is only a data container, I don't define any new method here.

**Comment by fooSynaptic** [comment]
i figure out the usage of nametuple
its the feature above python3.6
`class NamedTuple(builtins.object)
 |  Typed version of namedtuple.
 |  
 |  Usage in Python versions >= 3.6::
 |  
 |      class Employee(NamedTuple):
 |          name: str
 |          id: int
 |  
 |  This is equivalent to::
 |  
 |      Employee = collections.namedtuple('Employee', ['name', 'id'])
 |  
`
